// action types
export const ALL_COUNTRIES_FETCH_REQUESTED = 'ALL_COUNTRIES_FETCH_REQUESTED'
export const ALL_COUNTRIES_FETCH_SUCCEEDED = 'ALL_COUNTRIES_FETCH_SUCCEEDED'
export const SELECT_SINGLE_COUNTRY = 'SELECT_SINGLE_COUNTRY'
export const SINGLE_COUNTRY_SUCCEEDED = 'SINGLE_COUNTRY_SUCCEEDED'
export const REQUEST_FAILED = 'REQUEST_FAILED'
export const CHANGE_SEARCH_FIELD_INPUT = 'CHANGE_SEARCH_FIELD_INPUT'
