export const SINGLE_COUNTRY_REQUEST = 'SINGLE_COUNTRY_REQUEST'
export const SET_SELECTED_COUNTRY = 'SET_SELECTED_COUNTRY'
export const SINGLE_COUNTRY_SUCCEEDED = 'SINGLE_COUNTRY_SUCCEEDED'
export const REQUEST_FAILED = 'REQUEST_FAILED'
